# Pregunta 2

# Importación de librerías

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.metrics import (confusion_matrix, precision_score, recall_score, f1_score,
                             roc_curve, roc_auc_score, precision_recall_curve,
                             average_precision_score, log_loss)
from sklearn.calibration import calibration_curve

plt.rcParams['figure.figsize'] = (12, 5)
sns.set_palette("deep")
np.random.seed(42)

# Explicación de los datos

## Análisis Exploratorio de Datos

### Carga de data

In [3]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
sample_submission_df = pd.read_csv('sample_submission.csv')

### Inspección básica de data

In [6]:
train_df.head(3)

,id,pub_fecha,pub_titulo,pub_descripcion,pub_monto_estimado,pub_moneda,pub_metodo,pub_modalidad,pub_n_items,pub_cantidad_total,...,pub_cierre,pub_dias_postulacion,pub_tiene_consultas,pub_dias_consultas,comprador,comprador_id,comprador_rut,region,direccion,y_desierta
0,248328745624,2024-03-25T15:32:20Z,LP04-2024 AV. UNO SUR AYSEN,"CONSTRUCCIÓN CALZADA H.C.V. AVENIDA UNO SUR, P...",NaN,NaN,open,Licitación Pública MOP (O1),1,1.0,...,2024-04-12T10:00:00Z,17.769,False,11.0,SERVICIO DE VIVIENDA Y URBANIZACION XI REGION ...,CL-MP-1653,618230007,Región Aysén del General Carlos Ibáñez del Campo,RAMON FREIRE Nº 5,0
1,760555527084,2024-03-21T14:29:28Z,LICITACION PUBLICA PARA OBRAS DE INFRAESTRUCTU...,licitar las obras de infraestructura de mejora...,NaN,NaN,open,Licitación Pública entre a 2000 y 5000 UTM (LQ),1,1.0,...,2024-04-15T20:00:00Z,25.230,False,21.0,CORPORACION MUNICIPAL DE EDUCACION Y SALUD DE ...,CL-MP-1274286,709255002,Región Metropolitana de Santiago,O'HIGGINS 840,1
2,224829110991,2024-01-26T12:37:41Z,ADQUISICION DE INSUMOS DE ENFERMERÍA PARA DSM,ADQUISICION DE INSUMOS DE ENFERMERÍA PARA USUA...,3500000.0,CLP,open,Licitación Pública Menor a 100 UTM (L1),55,12150.0,...,2024-02-01T13:24:00Z,6.032,False,3.0,I MUNICIPALIDAD DE CHANCO | I MUNICIPALIDAD DE...,CL-MP-4391,69120300K,Región del Maule,Ignacio Carrera Pinto Nº 31,0

In [17]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152553 entries, 0 to 152552
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    152553 non-null  int64
 1   pub_fecha             152553 non-null  object
 2   pub_titulo            152544 non-null  object
 3   pub_descripcion       152544 non-null  object
 4   pub_monto_estimado    85287 non-null   float64
 5   pub_moneda            85251 non-null   object
 6   pub_metodo            152485 non-null  object
 7   pub_modalidad         152553 non-null  object
 8   pub_n_items           152553 non-null  int64
 9   pub_cantidad_total    152553 non-null  float64
 10  pub_categoria         152528 non-null  object
 11  pub_categoria_id      152528 non-null  float64
 12  pub_n_categorias      152553 non-null  int64
 13  pub_inicio            152553 non-null  object
 14  pub_cierre            152526 non-null  object
 15  pub_dias_postulacion  152530 non-null  float64
 16  pub_tiene_consultas   152553 non-null  bool
 17  pub_dias_consultas    152485 non-null  float64
 18  comprador             152553 non-null  object
 19  comprador_id          152553 non-null  object
 20  comprador_rut         152518 non-null  object
 21  region                152543 non-null  object
 22  direccion             144357 non-null  object
 23  y_desierta            152553 non-null  int64
dtypes: bool(1), float64(5), int64(4), object(14)
memory usage: 26.9+ MB

In [7]:
test_df.head(3)

,id,pub_fecha,pub_titulo,pub_descripcion,pub_monto_estimado,pub_moneda,pub_metodo,pub_modalidad,pub_n_items,pub_cantidad_total,...,pub_inicio,pub_cierre,pub_dias_postulacion,pub_tiene_consultas,pub_dias_consultas,comprador,comprador_id,comprador_rut,region,direccion
0,47254358932,2025-03-12T15:46:53Z,SC 36914 (CM) ADQUISICIÓN DE MOBILIARIO PARA C...,ADQUISICIÓN DE MOBILIARIO PARA CLÍNICA JURÍDIC...,4999999.0,CLP,open,Licitación Pública Menor a 100 UTM (L1),3,24.0,...,2025-03-12T15:46:47Z,2025-03-20T15:30:00Z,7.988,False,2.0,UNIVERSIDAD DE PLAYA ANCHA DE CIENCIAS DE LA E...,CL-MP-5385,707547006,Región Metropolitana de Santiago,Av. A Bello 2687
1,295671198916,2025-01-06T17:34:25Z,COMPRA DE MEDICAMENTOS PARA DEPTO SALUD MAULE,COMPRA DE MEDICAMENTOS PARA DEPTO SALUD MAULE,20000000.0,CLP,open,Licitación Pública Entre 100 y 1000 UTM (LE),45,123593.0,...,2025-01-06T17:34:19Z,2025-01-16T19:53:00Z,10.096,False,3.0,I MUNICIPALIDAD DE MAULE | I MUNICIPALIDAD DE ...,CL-MP-5605,691109003,Región del Maule,Balmaceda N° 350
2,214756376398,2025-02-26T12:48:51Z,ADQUISICIÓN DE BOLSAS CORPORATIVAS REUTILIZABL...,ADQUISICIÓN DE BOLSAS CORPORATIVAS REUTILIZABL...,NaN,NaN,open,Licitación Pública Entre 100 y 1000 UTM (LE),1,19000.0,...,2025-02-26T12:48:41Z,2025-03-03T15:00:00Z,5.091,False,2.0,I MUNICIPALIDAD DE QUILICURA | DEPARTAMENTO CO...,CL-MP-3475,690713004,Región Metropolitana de Santiago,NaN

In [20]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21829 entries, 0 to 21828
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    21829 non-null  int64
 1   pub_fecha             21829 non-null  object
 2   pub_titulo            21829 non-null  object
 3   pub_descripcion       21829 non-null  object
 4   pub_monto_estimado    10230 non-null  float64
 5   pub_moneda            10226 non-null  object
 6   pub_metodo            21734 non-null  object
 7   pub_modalidad         21829 non-null  object
 8   pub_n_items           21829 non-null  int64
 9   pub_cantidad_total    21829 non-null  float64
 10  pub_categoria         21828 non-null  object
 11  pub_categoria_id      21828 non-null  float64
 12  pub_n_categorias      21829 non-null  int64
 13  pub_inicio            21829 non-null  object
 14  pub_cierre            21823 non-null  object
 15  pub_dias_postulacion  21824 non-null  float64
 16  pub_tiene_consultas   21829 non-null  bool
 17  pub_dias_consultas    21819 non-null  float64
 18  comprador             21829 non-null  object
 19  comprador_id          21829 non-null  object
 20  comprador_rut         21824 non-null  object
 21  region                21828 non-null  object
 22  direccion             20331 non-null  object
dtypes: bool(1), float64(5), int64(3), object(14)
memory usage: 3.7+ MB

In [12]:
sample_submission_df.head(3)

             id  y_desierta
0   47254358932           1
1  295671198916           1
2  214756376398           1

In [24]:
sample_submission_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21829 entries, 0 to 21828
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          21829 non-null  int64
 1   y_desierta  21829 non-null  int64
dtypes: int64(2)
memory usage: 341.2 KB

In [34]:
sample_submission_df[sample_submission_df["y_desierta"] == 1].sum()

id            10929193504546743
y_desierta                21829
dtype: int64

## Limpieza de data

In [25]:
train_df.isnull().sum()

id                          0
pub_fecha                   0
pub_titulo                  9
pub_descripcion             9
pub_monto_estimado      67266
pub_moneda              67302
pub_metodo                 68
pub_modalidad               0
pub_n_items                 0
pub_cantidad_total          0
pub_categoria              25
pub_categoria_id           25
pub_n_categorias            0
pub_inicio                  0
pub_cierre                 27
pub_dias_postulacion       23
pub_tiene_consultas         0
pub_dias_consultas         68
comprador                   0
comprador_id                0
comprador_rut              35
region                     10
direccion                8196
y_desierta                  0
dtype: int64

# Construcción de features

# Modelos explorados

# Búsqueda de hiperparámetros

# Resultados y discusión